# Generated by Django 4.2.5 on 2023-09-27 00:25

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('projects', '0002_alter_imagesproject_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
    ]
