# Generated by Django 4.2.5 on 2023-10-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projects_categoryproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagesProject',
        ),
    ]
