# Generated by Django 4.2.5 on 2023-09-27 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 1, 9, 10, 968506)),
        ),
    ]
