# Generated by Django 4.2.5 on 2023-09-27 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_about_username_alter_about_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 1, 10, 10, 159790)),
        ),
        migrations.AlterField(
            model_name='about',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
