# Generated by Django 4.2.5 on 2023-09-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_about_join_date_alter_about_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='join_date',
        ),
    ]
