# Generated by Django 4.2.5 on 2023-09-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_category_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('fb_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('instagram_link', models.URLField()),
            ],
        ),
    ]
