# Generated by Django 4.2.5 on 2023-09-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
