# Generated by Django 4.2.5 on 2023-10-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
