# Generated by Django 4.2.5 on 2023-10-03 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_services_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='image'),
        ),
    ]
