# Generated by Django 4.2.5 on 2023-10-10 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_categoryskills_myskills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryService',
        ),
    ]
