# Generated by Django 4.2.5 on 2023-10-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_rename_category_categoryservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
