# Generated by Django 4.2.5 on 2023-10-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_resume_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume',
        ),
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
